from src.AutomatedMouseKeyboardRoutine import AutomatedMouseKeyboardRoutine


timeInSecondsBetweenEvents = 1
numberOfTimesToRepeatRoutine = 1

automatedGuiRoutine = AutomatedMouseKeyboardRoutine(timeInSecondsBetweenEvents, numberOfTimesToRepeatRoutine)
automatedGuiRoutine.Process()
